[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
uuid = { workspace = true }
chrono = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
